//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortener.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URLShortener.Core.Resource.Resource_Fa", typeof(Resource_Fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد انتخاب شده امکان حذف ندارد.
        /// </summary>
        public static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت زیرشاخه نمی باشد.
        /// </summary>
        public static string CanNotInsertSubInfo {
            get {
                return ResourceManager.GetString("CanNotInsertSubInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه ها را تکمیل کنید.
        /// </summary>
        public static string CompletIedtems {
            get {
                return ResourceManager.GetString("CompletIedtems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری یافت نشد.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازه دسترسی ندارید.
        /// </summary>
        public static string DoNotAccess {
            get {
                return ResourceManager.GetString("DoNotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه ثبت اطلاعات جدید را ندارید.
        /// </summary>
        public static string DoNotAccessAdd {
            get {
                return ResourceManager.GetString("DoNotAccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه  حذف را ندارید.
        /// </summary>
        public static string DoNotAccessDelete {
            get {
                return ResourceManager.GetString("DoNotAccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه ویرایش اطلاعات را ندارید.
        /// </summary>
        public static string DoNotAccessEdit {
            get {
                return ResourceManager.GetString("DoNotAccessEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه فعال نمی باشد.
        /// </summary>
        public static string DoNotActiveItem {
            get {
                return ResourceManager.GetString("DoNotActiveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار برابر نمی باشد.
        /// </summary>
        public static string DoNotEqualPassword {
            get {
                return ResourceManager.GetString("DoNotEqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات یافت نشد.
        /// </summary>
        public static string DoNotFindInfo {
            get {
                return ResourceManager.GetString("DoNotFindInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده قبلا ثبت شده است.
        /// </summary>
        public static string EmailIsAllready {
            get {
                return ResourceManager.GetString("EmailIsAllready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است دوباره سعی کنید.
        /// </summary>
        public static string ErrorTryAgain {
            get {
                return ResourceManager.GetString("ErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات فاکتور یافت نشد.
        /// </summary>
        public static string FactorDetailNotFound {
            get {
                return ResourceManager.GetString("FactorDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور یافت نشد.
        /// </summary>
        public static string FactorNotFound {
            get {
                return ResourceManager.GetString("FactorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا یافت نشد.
        /// </summary>
        public static string GoodNotFound {
            get {
                return ResourceManager.GetString("GoodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کالا برای مشتری مجاز نمی باشد.
        /// </summary>
        public static string GoodNotIsCustomer {
            get {
                return ResourceManager.GetString("GoodNotIsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات صحیح نمی باشد.
        /// </summary>
        public static string InfoNotIsValid {
            get {
                return ResourceManager.GetString("InfoNotIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت حذف شد.
        /// </summary>
        public static string InfoSuccessDelete {
            get {
                return ResourceManager.GetString("InfoSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ویرایش شد.
        /// </summary>
        public static string InfoSuccessEdit {
            get {
                return ResourceManager.GetString("InfoSuccessEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ثبت شد.
        /// </summary>
        public static string InfoSuccessInsert {
            get {
                return ResourceManager.GetString("InfoSuccessInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت بروزرسانی گردید.
        /// </summary>
        public static string InfoSuccessUpdate {
            get {
                return ResourceManager.GetString("InfoSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ مورد نظر یافت نشد.
        /// </summary>
        public static string MessageAnswerNotFound {
            get {
                return ResourceManager.GetString("MessageAnswerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب شما مسدود است.
        /// </summary>
        public static string MessageYourAccountHasBeenBlocked {
            get {
                return ResourceManager.GetString("MessageYourAccountHasBeenBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر ورودی بدون مقدار است.
        /// </summary>
        public static string ParameterIsEmputy {
            get {
                return ResourceManager.GetString("ParameterIsEmputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسش.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از بستن فرم جاری مطمئن هستید؟.
        /// </summary>
        public static string QuestionCloseForm {
            get {
                return ResourceManager.GetString("QuestionCloseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف مورد انتخاب شده مطمئن هستید؟.
        /// </summary>
        public static string QuestionDeleteItem {
            get {
                return ResourceManager.GetString("QuestionDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از بروزرسانی اطلاعات مطمئن هستید ؟.
        /// </summary>
        public static string QuestionUpdateInfo {
            get {
                return ResourceManager.GetString("QuestionUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش غیر فعال است.
        /// </summary>
        public static string ReportNotEnable {
            get {
                return ResourceManager.GetString("ReportNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش یافت نشد.
        /// </summary>
        public static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست قبلا پاسخ داده شده است.
        /// </summary>
        public static string RequestIsAnswer {
            get {
                return ResourceManager.GetString("RequestIsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نامعتبر است.
        /// </summary>
        public static string RequestIsDead {
            get {
                return ResourceManager.GetString("RequestIsDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پاسخ داده نشده است.
        /// </summary>
        public static string RequestNotAnswer {
            get {
                return ResourceManager.GetString("RequestNotAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست یافت نشد.
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        public static string ResualtOK {
            get {
                return ResourceManager.GetString("ResualtOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ثبت گردید.
        /// </summary>
        public static string ResultIsAdd {
            get {
                return ResourceManager.GetString("ResultIsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت تایید گردید.
        /// </summary>
        public static string ResultIsConfirm {
            get {
                return ResourceManager.GetString("ResultIsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت حذف گردید.
        /// </summary>
        public static string ResultIsDelete {
            get {
                return ResourceManager.GetString("ResultIsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت بروزرسانی گردید.
        /// </summary>
        public static string ResultIsUpdate {
            get {
                return ResourceManager.GetString("ResultIsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ اطلاعاتی ثبت نگردید.
        /// </summary>
        public static string ResultNotAdd {
            get {
                return ResourceManager.GetString("ResultNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ اطلاعاتی تایید نگردید.
        /// </summary>
        public static string ResultNotConfirm {
            get {
                return ResourceManager.GetString("ResultNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ اطلاعاتی حذف نگردید.
        /// </summary>
        public static string ResultNotDelete {
            get {
                return ResourceManager.GetString("ResultNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ اطلاعاتی بروزرسانی نگردید.
        /// </summary>
        public static string ResultNotUpdate {
            get {
                return ResourceManager.GetString("ResultNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با کلید Enter انتخاب نمایید.
        /// </summary>
        public static string SelectByClickEnterKey {
            get {
                return ResourceManager.GetString("SelectByClickEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یک گزینه را انتخاب نمایید.
        /// </summary>
        public static string SelectOneItem {
            get {
                return ResourceManager.GetString("SelectOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کد قبلا ثبت شده است.
        /// </summary>
        public static string ThisCodeIsAllready {
            get {
                return ResourceManager.GetString("ThisCodeIsAllready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام لاتین قبلا ثبت شده است.
        /// </summary>
        public static string ThisEnNameIsAllready {
            get {
                return ResourceManager.GetString("ThisEnNameIsAllready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام قبلا ثبت شده است.
        /// </summary>
        public static string ThisFaNameIsAllready {
            get {
                return ResourceManager.GetString("ThisFaNameIsAllready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام نمایشی قبلا ثبت شده است.
        /// </summary>
        public static string ThisViewNameIsAllready {
            get {
                return ResourceManager.GetString("ThisViewNameIsAllready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احزار هویت بدون مقدار است.
        /// </summary>
        public static string TokenIsEmpty {
            get {
                return ResourceManager.GetString("TokenIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند احراز هویت یافت نشد.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی ناشناخته رخ داده است.
        /// </summary>
        public static string UnKnowException {
            get {
                return ResourceManager.GetString("UnKnowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس نامعتبر می باشد.
        /// </summary>
        public static string UrlIsNotValid {
            get {
                return ResourceManager.GetString("UrlIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری وارد شده قبلا ثبت شده است از گزینه فراموشی رمز استفاده نمایید.
        /// </summary>
        public static string UserNameIsAllready {
            get {
                return ResourceManager.GetString("UserNameIsAllready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت یافت نشد.
        /// </summary>
        public static string UserNotVerify {
            get {
                return ResourceManager.GetString("UserNotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورژن نرم افزار صحیح نمی باشد.
        /// </summary>
        public static string VersionNotFound {
            get {
                return ResourceManager.GetString("VersionNotFound", resourceCulture);
            }
        }
    }
}
