//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortener.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_En {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_En() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URLShortener.Core.Resource.Resource_En", typeof(Resource_En).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice details not found.
        /// </summary>
        public static string FactorDetailNotFound {
            get {
                return ResourceManager.GetString("FactorDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice not found.
        /// </summary>
        public static string FactorNotFound {
            get {
                return ResourceManager.GetString("FactorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string GoodNotFound {
            get {
                return ResourceManager.GetString("GoodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is not allowed for the customer.
        /// </summary>
        public static string GoodNotIsCustomer {
            get {
                return ResourceManager.GetString("GoodNotIsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer was not found.
        /// </summary>
        public static string MessageAnswerNotFound {
            get {
                return ResourceManager.GetString("MessageAnswerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is blocked.
        /// </summary>
        public static string MessageYourAccountHasBeenBlocked {
            get {
                return ResourceManager.GetString("MessageYourAccountHasBeenBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input parameter is of no value.
        /// </summary>
        public static string ParameterIsEmputy {
            get {
                return ResourceManager.GetString("ParameterIsEmputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report disabled.
        /// </summary>
        public static string ReportNotEnable {
            get {
                return ResourceManager.GetString("ReportNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report not found.
        /// </summary>
        public static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has already been answered.
        /// </summary>
        public static string RequestIsAnswer {
            get {
                return ResourceManager.GetString("RequestIsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string RequestIsDead {
            get {
                return ResourceManager.GetString("RequestIsDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request not answered.
        /// </summary>
        public static string RequestNotAnswer {
            get {
                return ResourceManager.GetString("RequestNotAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request not found.
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ResualtOK {
            get {
                return ResourceManager.GetString("ResualtOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information was successfully recorded.
        /// </summary>
        public static string ResultIsAdd {
            get {
                return ResourceManager.GetString("ResultIsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information was successfully verified.
        /// </summary>
        public static string ResultIsConfirm {
            get {
                return ResourceManager.GetString("ResultIsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information successfully deleted.
        /// </summary>
        public static string ResultIsDelete {
            get {
                return ResourceManager.GetString("ResultIsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information was successfully updated.
        /// </summary>
        public static string ResultIsUpdate {
            get {
                return ResourceManager.GetString("ResultIsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information was recorded.
        /// </summary>
        public static string ResultNotAdd {
            get {
                return ResourceManager.GetString("ResultNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information confirmed.
        /// </summary>
        public static string ResultNotConfirm {
            get {
                return ResourceManager.GetString("ResultNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information was deleted.
        /// </summary>
        public static string ResultNotDelete {
            get {
                return ResourceManager.GetString("ResultNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information was updated.
        /// </summary>
        public static string ResultNotUpdate {
            get {
                return ResourceManager.GetString("ResultNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity is invalid without value.
        /// </summary>
        public static string TokenIsEmpty {
            get {
                return ResourceManager.GetString("TokenIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authentication document found.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred.
        /// </summary>
        public static string UnKnowException {
            get {
                return ResourceManager.GetString("UnKnowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired user was not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authentication found.
        /// </summary>
        public static string UserNotVerify {
            get {
                return ResourceManager.GetString("UserNotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software version is not correct.
        /// </summary>
        public static string VersionNotFound {
            get {
                return ResourceManager.GetString("VersionNotFound", resourceCulture);
            }
        }
    }
}
